services:
  - type: web
    name: williame-ai-sensi
    runtime: node

    buildCommand: npm install
    startCommand: npm start

    envVars:
      - key: NODE_ENV
        value: production

      - key: AI_API_KEY
        sync: false
